### ISSUE TITLE
Output for failed query commands

### ISSUE THREAD

**Issue by jbernsie** [jbernsie/enkee#3]
When passing a name to `get` that doesn't exist, the function that fires the query still returns an `Ok()` so the program doesn't see the difference between a query that returns a result, and one that does.

### Affected Commands
- `get` - returns no output, should say "No record found with `name`"
- `delete` - actually says "`name` deleted", should return a simmilar "No record found" message

**Comment by ArtUshak** [comment]
Sorry, but that pull request #11 had fix for `get` command only, not `delete`.

**Comment by jbernsie** [comment]
@ArtUshak that's fine man, its virtually the same code easy enough to patch before next release tag
